language: node_js
node_js:
  - '14'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - main

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: main
  local-dir: dist
  on:
    repo: xoori555/xoori555.github.io
    branch: main
